# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Candace Savonen]|
|Lecturer(s)|[Candace Savonen]|
|Content Directors|[Jeff Leek], [Sarah Wheelan]|
|Content Reviewer| [Sarah Wheelan]|
|Content Editor|[Jimin Hwang]|
|Acknowledgments| |
|**Production**||
|Content Publisher|[Ira Gooding]|
|Content Publishing Reviewers|[Ira Gooding]|
|**Technical**||
|Course Publishing Engineer|[Candace Savonen]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal])[John Muschelli], [Candace Savonen], [Carrie Wright]|
|**Art and Design**||
|Illustrator| [Candace Savonen] [Jimin Hwang]|
|Figure Artist| [Candace Savonen]|
|Videographer|[Candace Savonen]|
|Videography Editor| [Candace Savonen]|
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) UE5 CA254170|
|Funding Staff| Emily Voeglein, Fallon Bachman|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
[Jimin Hwang]: https://www.linkedin.com/in/jimin-hwang-549835142/
[Jeff Leek]: https://jtleek.com/
[John Muschelli]: https://johnmuschelli.com/
[Sarah Wheelan]: https://www.hopkinsmedicine.org/profiles/details/sarah-wheelan

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal
